### ISSUE TITLE
Protocol for using this code?

### ISSUE THREAD

**Issue by mcianfrocco** [nogaleslab/Microtubule#1]
Hi @rui--zhang ! I'm glad to see your code uploaded to github. Will you be publishing a protocol within the README or wiki pages on github so that users can follow along with your scripts?

**Comment by rui--zhang** [comment]
Hi, Mike,

I'll definitely write a REAME for the scripts shortly. I'll let you guys
know.

Rui

**Comment by mcianfrocco** [comment]
Cool thanks!
